---
- name: checa vers√£o instalada
  shell: /opt/firefox/firefox --version | cut -d' ' -f3
  register: firefox_register_version
  changed_when: False
  failed_when: False
  tags: ["firefox"]

- include: install.yml
  when: firefox_register_version.stdout != firefox_version or firefox_force_install is defined
  tags: ["firefox"]
